### ISSUE TITLE
Don't runtime dep on LWP

### ISSUE THREAD

**Issue by frioux** [perl-catalyst/Catalyst-Action-REST#3]

**Comment by frioux** [comment]
maybe look into HTTP::Tiny

**Comment by marcusramberg** [comment]
Or Mojo::UserAgent. :p

**Comment by frioux** [comment]
Fixed this by just making it a test dep.  I'd be happy to use HTTP::Tiny, but it's not a drop in replacement since this code heavily uses the HTTP::Request object.  I may get around to doing it myself at some point, but we might as well solve the problem now and get around to that later.
